sudo: false
os:
- linux
language: haskell
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build --ghc-options='-Wall -Werror'
- stack haddock
script:
- "! grep -E -i '[?][?][?]|TODO' $(find src -iname '*.hs')"
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    tags: true
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: OqdxTOjC/2Qn3v+rczAc8ha3XjF+qEGRt4DhJATXEZBNBJqHq4UhukTCi2F6ipoNTYb8klq9SOA0xU1GhJ/sPXSVyNtgUG0Lsqtz/ufyCH4/K4u023BfjXL+Qjyh1BsNDaaKxDBBAAnEbBVTHYAFW2nP2wD+Au4lhb7B3o9OEOSM/RxTc6mM65hsnjAigR0GtdPetXO5ArQtXhkRDQYIDpRbSRt8ct4nNioRFoj61CPJT50VTsVKh7LnB3FVzofWJgTSH7yp40zLLigeGc5Xh/K66zyRFR6XrBxanbvCNyxiEu8tG5EKX1Ig8nv+dx9THFSFLe+G3rnzV0vA2UwdVT2e3OQZC+2ihhbubFdX1udaoTCt2YEwOjDy3uYefE/piLLnl+rjh31FtkZrPyxKQHnSrvnlJmu34Cfe9K5kW+X0lSg/qPRtgHXzAqFRBgdjR4L8JCYg+kFKkmjTvTym4e/54YpLARzpzYrjJ8tMnQbiC0OZNuab0f9Re78Lxvn2coP4nXb0G8qJNEqw6xAMzx0qeWuqxAi+litMIClTdcEimVlGWEY8DFOMZajA92SA9McmeuDQIlyc3tY692ETVOqGKtB7yta3Hc1S/PvZOPFztBAv0UJPg9+W81Fib3HlejRKGufMw4m2e6Hf4kzf4lyCe6i52NcuNqTrYv2stL4=
  - secure: KD8d5185KuptG/yHNAnWlFhIggXIscYEmqCJb0r1+a2voY6cMs5PZx/FpP+0T947KkBNVZDmd45U4OVmz2ePHCPT8DIgh1AybQ38a05GQ7sL1TmUtN0UKya0jjJjF63doXy6j+/i+lxq14Tlts7pW3SahEdOJ926qx2XpLSWojjVoNI32vpljG8YJ48iIc9OfdnVlrGeTU+FajWoc2RJdf3P2Zx6Q2HC3FPJ6GfIpNsyDrBqoLHKFUZtEnzk8P1mvgGB2QXCvb0SVJ4RqspG8vrltSDr1z0X+ug03QNxbhIvQCoeVPvNYZOAyguygSaGZdyOFwo0mjtQw89axiqjYazmBj0OJ+kBdbbWKFvEr4IHQHCdNSCGJKtYVQ3Bvxqd4J5TYQJl0payguW1CUOUprfQL54kdBp04fBAjDIeikFvVw7eEioI/B4b0Iw0E0Q42wRu0Y+ZaeoAtUob9G+MIDkmNoz4d7g+1tfGMHUYqaWzh4x28Iwd+hkutTYC2f+lo0IgjmY1wfYLlbrj3es2EKwyRrSvg2R+WPPSyPzlK2Mkj2ITLX2w87WxvWnBCIcu2mgN4ar6JBxzjC0/UJvOYh5lJL+1IIrHGfH+S7ZHpGX3femqbK1s3CcPU34HexSybf7FDEOTsV8zre8O5KKdgsrM0cS6AJeLq5z6/aBAjeM=
  - secure: ZjadbQ6Ryu4myvV0dRFnfPhq7FMARzfFt4xR+rNHOc19SSGc8YfjKUAbi+vRIi7qLGjbcLi+23XUGAQtIjDFa4maRivO04lmGlb4OadoumHKEqOduZ0+4r5uqHMXYNaO7mMScEBuSsspv6GgMFsl048iCcZ/vp6E160jE6OyFvJdpzCuWNFD5Nde203Y8KQ+z9p/eVJBgG31yYBmdrFWYq1IaExpqx/j8TF8/teTdhL/6Xm+MoVGN3bIsQvNE8X5Yr1zh2WOK5VMDHukyCQ3dwj0rH7gHqNj4sdRYtK9gYNwi36e/X9SxJFxIWZFu5SbSIYEUkSfTJilMToaQeBAtpbavkauTREdpiu/jot7z2GqOtFWopVwyG5pevNmgFh14DmF6m3Smh/2H8Hz6e7NmX1wrFACEUyxEDu8gx7G14ddzPvG/5zKVA22Wo177aety6Xp54E09x07sKtLe7GQA8vlARIVXpLfXS11X5dlRRS+Unp1sKNTUeSx5iBbXZLu2n/GhwlmS7kUMRk2mgYxVnQvvH9I+SW1DrnM85Z6S/QshTkr8QVkoRTGQPKFeSuKGOgN52wxdibaeuwlPOxHPDdsdetl+kQeRMjXVGUtn3cAQTPwX5qgfwj/1vavyC9GHZS+viZ7lPwCsC5iSYZzmvzE99gbW0RS9/hTbqChJ1A=
